# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pgYbUdF_ka5c-clK7kryyQUMhJvuuiBp
"""

import pandas as pd
teachers=pd.DataFrame({
    "FISH":[ 'Qadamova Z',"Xalilov D","Qurbonova G","Djalilov M","Abdullayeva M","Xontorayev S","Tillaboyev M","Jo'rayeva G","Raxmatov R","Turdimatov M"],
    'FANI':["sun'iy intellekt asoslari","sun'iy intellekt asoslari","Kampyuterni tashkil etish","Kampyuterni tashkil etish",
            "Malumotlar tuzilasi algoritmlar","Malumotlar tuzilasi algoritmlar","Elektronika Sxemalar","Elektronika Sxemalar","Kiber xavsizlik","Kiber xavsizlik"],
    "Mashg'ulot  turi":['amaliy',"ma'ruza",'amaliy',"ma'ruza",'amaliy',"ma'ruza",'amaliy',"ma'ruza",'amaliy',"ma'ruza",],
    "Dars o'tish maxorati":['yaxshi',"yaxshi",'yaxshi',"yaxshi",'yaxshi',"yaxshi",'yaxshi',"yaxshi",'yaxshi',"yaxshi",]
})
print(teachers)